### ISSUE TITLE
Autori

### ISSUE THREAD

**Issue by Francesco215** [LetteraUnica/menzalib#17]
nel file [setup.py](https://github.com/LetteraUnica/menzalib/blob/latex/setup.py) ho messo una linea che dice:`author=["Lorenzo Cavuoti", "Francesco Sacco"]`, non so se va bene, vedi se pip considera i due autori come separati

**Comment by LetteraUnica** [comment]
Mi pare che l'avessi messa pure io ma poi pip non me la fece caricare su pypi. In ogni caso lasciamo il cambiamento, poi se non me la carica lo cambio al momento
