### ISSUE TITLE
Fare una funzione per l'errore in frequenza

### ISSUE THREAD

**Issue by Francesco215** [LetteraUnica/menzalib#2]

**Comment by LetteraUnica** [comment]
Fatto la funzione, l'errore sulla misura del cursore è dato dall'inverso dell'errore sul tempo in quanto non ho trovato altro sul datasheet.

errore_osc_frequenza(f, scala=None, misura="cursore")
    Calcola l'errore della misura di frequenza dell'oscilloscopio
    supponendo che si sia scelta la scala corretta.
    i.e. quella dove il segnale si vede meglio senza che questo esca dallo schermo
    La frequenza deve essere data in Hertz.
    Il parametro opzionale scala serve per scegliere la scala se questa è diversa da
    quella assunta dalla funzione
    Se il parametro opzionale misura è diverso da "cursore" l'errore in frequenza
    viene dato dal trigger dell'oscilloscopio (molto preciso ma meno robusto)
